name: flood_test
channels:
  - conda-forge
dependencies:
  - rasterio
  - matplotlib
  - pip
  - jupyterlab
  - pyproj
  - xarray
  - rioxarray
  - numpy
  - eccodes
  - cfgrib
  - scipy
  - cartopy
  - pandas
  - ipywidgets
  - tqdm
  - gdal
  - pip:
      - netcdf4
      - damagescanner
      - jupyterlab_myst
